### ISSUE TITLE
Include the Author name as well

### ISSUE THREAD

**Issue by lee-40square** [MichaelCurrin/rewrite-git-author#1]
Sorry, I'm not good enough with Git to offer a PR. However, I wonder if the script could be modified so that it can change the Author name as well as the email?

Thank!

**Comment by MichaelCurrin** [comment]
Hi this is possible but not straightforward as I need to do a lot of argument parsing to separate email and name and keep the ability to only set email without name.

**Comment by MichaelCurrin** [comment]
Would you be willing to install and run `git filter-repo` tool which is similar to `git filter-branch` which my tool uses?

I worked out some commands for you

**Comment by MichaelCurrin** [comment]
Install and run the [git-filter-repo][] tool, which is linked from the [git-filter-branch][] official docs as a better replacement.

[git-filter-repo]: https://github.com/newren/git-filter-repo
[git-filter-branch]: https://git-scm.com/docs/git-filter-branch

## Examples

Example from their docs, modified here for clarity. Note use of Python code for callbacks.

```sh
$ git filter-repo --email-callback '
  return b"new@example.com" if email == b"old@localhost" else email
'
```

Take that further:

```sh
$ git filter-repo --name-callback '
  return b"New name" if name == b"Old name" else name
'
```

**Comment by lee-40square** [comment]
Thanks for the effort Michael and thanks for pointing me to this. (and sorry for the late reply).
